name: minimarket
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.5.1
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  fonts:
    - family: Orion
      fonts:
        - asset: assets/fonts/orionsans_regular.ttf
  uses-material-design: true
